version: "3.4"

services:
  web:
    image: vovimayhem/dotnet-core-postgresql:latest
    ports:
    # We'll bind our host's port 5000 to the app's port 5000, so we can use our
    # browsers to see it:
    - published: ${DEMO_DEPLOY_WEB_PORT}
      target: 5000
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
    environment:
      DATABASE_URL: ${DEMO_DEPLOY_DATABASE_URL}
      PORT: 5000
